all:
  vars:
    ansible_user: #TODO
    ansible_pass: #TODO

prod:
  hosts:
    s-msk-t-jvm-00:
    s-msk-t-jvm-01:
    s-msk-t-jvm-02:
    s-msk-t-jvm-03:
    s-msk-t-jvm-04:
    s-msk-t-jvm-05:
    s-msk-t-jvm-06:
    s-msk-t-jvm-07:
    s-msk-t-jvm-08:
    s-msk-t-jvm-09:
